//To Do:
//add us address...
//add home address, delivery options and name all edited in one place - auth...
//confirm logo
//apply extra user info on view package table
//add address to customer nav - both rates and address on customer and employee
//ensure customer enters full name
//view user
//email notifications - need professional email first
//make user edit section: available to admins, elevated employees, supervisors



//make multi select menu: print, delete...etc - along with multi update menu
//add email updates
//Show an example of using Amazon/Shein - show shipping address - name with PMR - when making a package, on new sign up - Add PMR in
//contact us map
//add auth to view image/download
//enable contact form - need business email/domain
//general email for customers to re-sign up
//bulk actions
//new customer onboarding process - completed check - if not customer sees update info
//add notifications - on specific package info change - location, status change, needs attention
//update amt of points for each service - points made
//Highlight email updates for packages
////make comments own table
//home delivery to
// Kingston, st Thomas
// add customer address to package info table - Kingston/st. thomas

//long term
//write to reusable project
////auth role checker
//write starts to share project
//update testimonials
//make admin page - manage all fields




//Ideas
//websockets?
//bulk upload for warehouse users

//naming
//schema - plural
//type - singular with Type added - e.g userType
//serverFunctions - handlePlural e.g handleUsers - singular function names - e.g addUser - getAll remains plural - e.g getUsers

//copy design -
////put content down - then style
////note ahead of time what element types youll need - h1, title...etc
//copy content - gpt/paramount couriers




//notes
//sync env

//Value given by the user via a pre-alert or by updating the package information. Also can be given when the package is inspected in Miami and an invoice is found.
//CIF is the abbreviation of cost,insurance and freight. This is the value that is declared to customs and conssists on the packages value, transportation cost and insurance. Taxes and duties are calculated based on this value.

//add checks all fields given, ensures whos asking only can create what they'd expect
//update ensures only validated keys are given to the update object

//we use prc
//anything that comes to the warehouse with prt is ours - customer name on there
// managaeparamountcouriers@gmail.com
//paramount offers home address delevery and branch pickup




//completed
//Find templates that look good…
//Choose colors…
//Fonts - h1, h2, h3, p…
//custom auth on resources...
//need rates page...
//fix dashboards...
//nav...
//fill with proper information - rush shipping...
//services, about us, testimonials, contact us, rates...
//rename database...
//enusre files have fileType in them...
//rework upload api - for just one route...
//add FAQ - common questions of the business...
//ask how will warehouse employees update a package...
//proper nav - sub menus - mobile as well...
//change price to declared (package) value...
//add cif value...
//add charges: services fee, freight, fuel, insurance...
//track payment in db...
//over 5 years experience...
//we offer door to door - save customer address - ask more...
//change to our unique address, phone number...
//ships 3 times a week - Monday, Wednesday and Saturday...
//update copyright footer...
//green is nice, red and black...
//Jamaica arrives - ready for pickup, delivered at the end...
//new logo...
//charges start off at a certain value - takes into consideration the weight of the package - active rates - make a database...
//finish dashboard home...
//add accounts page...
//make gmail for manageparamountcouriers...
//designs for services...
//Landing page should have...
//Faq section...
//Rates...
//Highlight how many times per week shipments are available - monday/wednesday, get address as well...
//auth table updated...
//make packages table use permissions for all users...
//ensure resource id passed to function always...
//replace pre alerts page with link...
//make overview...
//show packages not closed...
//recently delivered...