//To Do:
//admin dashboard manage all options...
//add notifications - on specific package info change - location, status change, needs attention
//bulk updates

//ensure upload folder not synced on github
//add extra location to package - in delivery to customer, with customer...etc
//proper package small view component
//add better package examples
//make multi select menu: export to excel, delete...etc
//improve filters on view table
//add auth to view image/download
//send off general email for customers to re-sign up
//new customer onboarding process - completed check - if not customer sees update info
//make comments own table
//note options for store type - show tracking number live
//proper branch selection - global
//consider full access roles
//research premade google account issue
//clear invoice/images options - on package delete and manual
//google cloud from their account
//add stores select to add edit package
//add view tracking number options

//long term
//write to reusable project
////auth role checker
//write starts to share project
//update testimonials
//make admin page - manage all fields




//Ideas
//admin
//go over all database tables
//check auth on each who can c, r, u, d
//search records
//show add record option (if authed)
//select multiple records - show delete option (if authed)
//add additional content - like delete packages if deleting user...etc
//
//
//
//websockets?
//bulk upload for warehouse users

//naming
//schema - plural
//type - singular with Type added - e.g userType
//serverFunctions - handlePlural e.g handleUsers - singular function names - e.g addUser - getAll remains plural - e.g getUsers

//copy design -
////put content down - then style
////note ahead of time what element types youll need - h1, title...etc
//copy content - gpt/paramount couriers




//notes
//sync env

//Value given by the user via a pre-alert or by updating the package information. Also can be given when the package is inspected in Miami and an invoice is found.
//CIF is the abbreviation of cost,insurance and freight. This is the value that is declared to customs and conssists on the packages value, transportation cost and insurance. Taxes and duties are calculated based on this value.

//add checks all fields given, ensures whos asking only can create what they'd expect
//update ensures only validated keys are given to the update object

//we use prc
//anything that comes to the warehouse with prt is ours - customer name on there
// managaeparamountcouriers@gmail.com
//paramount offers home address delevery and branch pickup

//ensure customer enters full name

//vps at 72.60.25.209 - Paramount2Caps@numbers




//completed
//Find templates that look good…
//Choose colors…
//Fonts - h1, h2, h3, p…
//custom auth on resources...
//need rates page...
//fix dashboards...
//nav...
//fill with proper information - rush shipping...
//services, about us, testimonials, contact us, rates...
//rename database...
//enusre files have fileType in them...
//rework upload api - for just one route...
//add FAQ - common questions of the business...
//ask how will warehouse employees update a package...
//proper nav - sub menus - mobile as well...
//change price to declared (package) value...
//add cif value...
//add charges: services fee, freight, fuel, insurance...
//track payment in db...
//over 5 years experience...
//we offer door to door - save customer address - ask more...
//change to our unique address, phone number...
//ships 3 times a week - Monday, Tuesday and Thursday...
//update copyright footer...
//green is nice, red and black...
//Jamaica arrives - ready for pickup, delivered at the end...
//new logo...
//charges start off at a certain value - takes into consideration the weight of the package - active rates - make a database...
//finish dashboard home...
//add accounts page...
//make gmail for manageparamountcouriers...
//designs for services...
//Landing page should have...
//Faq section...
//Rates...
//Highlight how many times per week shipments are available - monday/wednesday, get address as well...
//auth table updated...
//make packages table use permissions for all users...
//ensure resource id passed to function always...
//replace pre alerts page with link...
//make overview...
//show packages not closed...
//recently delivered...
//add us address...
//add home address, delivery options and name all edited in one place - auth...
//confirm logo...
//add auth to add/see users screen...
//confirm nav options: admin, employee, customer...
//apply extra user info on view package table...
//add address to customer nav - both rates and address on customer and employee...
//view user...
//make user edit section: available to admins, elevated employees, supervisors...
//confirm branch locations...
//contact us map...
//Show an example of using Amazon/Shein - show shipping address - name with PMR - when making a package, on new sign up - Add PMR in...
//update amt of points for each service - points made...
//Highlight email updates for packages...
//home delivery to Kingston, st Thomas...
//add customer address to package info table - Kingston/st. thomas...
//email notifications - need professional email first...
//enable contact form - need business email/domain...
//go over features - customer, employee, admin...
//onboarding/sign up - accounts page - packages/pre alerts...
//explain role based access...
//show supervisor updating users...
//talk on professional email...
//setup server with business email (manageparamount) - handle server body upload size, certbot and postgres along with permissions...
//update us address examples - no longer miami address...
//update phone numbers - digicel/flow...
//update numbers on site...
//apply updated rates list...
//make mobile dashboard visible on mobile...
//add jmd...
//ask about social media - add them - instagram/tiktok...
//move view table info further up...
//make login clear...
//how it works page...
//proper get started page explaining everything...
//move us address closer...
//use address - no wrap...
//filter email error...
//active inactive check for user login - settled on deleting user - contact us...
//rate sheet changes...