import "./globals.css";
import type { Metadata } from "next";
import { Raleway, Manrope, Roboto, Rubik } from "next/font/google"
import { Toaster } from "react-hot-toast";
import localFont from "next/font/local";

const roboto = Roboto({
  variable: "--roboto",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--raleway",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--manrope",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--rubik",
  subsets: ["latin"],
});

const materialSymbolsOutlined = localFont({
  src: "./fonts/MaterialSymbolsOutlined-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsOutlined",
});
const materialSymbolsRounded = localFont({
  src: "./fonts/MaterialSymbolsRounded-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsRounded",
});
const materialSymbolsSharp = localFont({
  src: "./fonts/MaterialSymbolsSharp-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsSharp",
});

export const metadata: Metadata = {
  title: "Reggae Rush",
  description: "Generated by max",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${raleway.variable} ${manrope.variable} ${roboto.variable} ${rubik.variable} ${materialSymbolsOutlined.variable} ${materialSymbolsRounded.variable} ${materialSymbolsSharp.variable} antialiased`}>
        <Toaster position="top-center" reverseOrder={false} />

        {children}
      </body>
    </html>
  );
}