import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { auth } from "@/auth/auth";
import { Raleway, Manrope, Roboto } from "next/font/google"
import Navbar from "@/components/navbar/Navbar";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({
  variable: "--roboto",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--raleway",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reggae Rush",
  description: "Generated by max",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${raleway.variable} ${manrope.variable} ${roboto.variable} antialiased`}>
        <SessionProvider>
          <Toaster position="top-center" reverseOrder={false} />

          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
